# Generated by Django 5.2.5 on 2025-09-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='jersey_no',
            new_name='number',
        ),
        migrations.AddField(
            model_name='team',
            name='disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_type',
            field=models.CharField(choices=[('batsman', 'Batsman'), ('bowler', 'Bowler'), ('allrounder', 'All Rounder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='overs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_players',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='wickets',
            field=models.IntegerField(editable=False),
        ),
    ]
