# Generated by Django 5.2.5 on 2025-09-21 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_jersey_no_player_number_team_disqualified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('team1_runs', models.PositiveIntegerField(default=0)),
                ('team1_overs', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('team1_wickets', models.PositiveIntegerField(default=0)),
                ('team2_runs', models.PositiveIntegerField(default=0)),
                ('team2_overs', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('team2_wickets', models.PositiveIntegerField(default=0)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='home.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='home.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='home.team')),
            ],
        ),
    ]
